import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import { Lexend } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import ScrollToTopButton from "@/components/ScrollToTopButton";

const font = Lexend({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Create 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
        <ScrollToTopButton />
      </body>
    </html>
  );
}
