import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import { Lexend } from "next/font/google";
import Navbar from "@/components/Navbar";

export const font = Lexend({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
