import type { Metadata } from "next";
import "../(website)/globals.css";
import { Lexend } from "next/font/google";

const font = Lexend({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Create 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  );
}
